/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CardSkeleton: typeof import('./components/CardSkeleton.vue')['default']
    CharacterItem: typeof import('./components/CharacterItem.vue')['default']
    CharactersList: typeof import('./components/CharactersList.vue')['default']
    copy: typeof import('./components/ListItem copy.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./components/icons/IconTooling.vue')['default']
    ListItem: typeof import('./components/ListItem.vue')['default']
    LocationComponent: typeof import('./components/LocationComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./components/TheWelcome.vue')['default']
    VvBadge: typeof import('@volverjs/ui-vue/vv-badge')['default']
    VvCard: typeof import('@volverjs/ui-vue/vv-card')['default']
    VvDialog: typeof import('@volverjs/ui-vue/vv-dialog')['default']
    VvProgress: typeof import('@volverjs/ui-vue/vv-progress')['default']
    Welcome: typeof import('./components/Welcome.vue')['default']
    WelcomeItem: typeof import('./components/WelcomeItem.vue')['default']
  }
}
